"""add InterviewSlot

Revision ID: 5e46a33c826e
Revises: 
Create Date: 2025-05-19 17:57:11.366157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e46a33c826e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('is_taken', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('datetime')
    )
    with op.batch_alter_table('adoption_request', schema=None) as batch_op:
        batch_op.alter_column('preferred_datetime',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.alter_column('size',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('adoption_contract',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=True)

    with op.batch_alter_table('volunteer_request', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_request', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.alter_column('adoption_contract',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('size',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('adoption_request', schema=None) as batch_op:
        batch_op.alter_column('preferred_datetime',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    op.drop_table('interview_slot')
    # ### end Alembic commands ###
